language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "hP4LVNufLNwFf//KR/ASmZPr2AKez4q5SvwU5Nf8R+h13yLXbOifHILqrQfz8bNH7+n4VVOVWQdmvQaeWuQy9b99M7Y6ThN6FuZVa6kcoocYddinPFFjDX1icznKwc8Zqp8WAR5/zu83/flOtPbglONn/wqsR5QP/D2Jq3uOiMRftbEIipA3whx8MJwm43mzCRptHVfD3sKmoTCkCcXpN1DCFFgwP/a8Zk0T58w0kNvarIKFv4hlP1T/PDswgzuym3oaowJEdtoX1ybdXclik9vV3SAHr2Z2432ZqeVCqfbarIBJURvTKazEw+BeHAHrbQViCtR6R68VlYIpME4M1RNp16bzKgR1+NoJY0msXBD/fVVu2e/xsSbZMz3w3eDFwCSYJBSB4/cqvwsRtnSGJomym1nPRPO1T0cNbG9Rd4gYScoGixMBwy1fjOZI8BdAXkidMtxlP4P3bhWEzmfbxD7vq8bMdLFwmyEl9LodA+GaKr9zhYfOpd430sfCkiXhB4xfIAYuKeoPoGL/tryAj6mbaw1ezfya8kH3Ti/BNGJGqT9HLlqyXLQS/eLpSt8D3AWQshc/f94mSxoukZMHrB2AnhBJzktaotEN4Zj574wcxytXUXhPi5PNkkAvNgMW0FGlIfH5r45HHh6HvuETS2wn6S2pISmgQ41YI9ni63s="
  on:
    branch: master

